version: '3.8'

services:
  task-app-db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=taskdb
    volumes:
      - pgdata:/bitnami/postgresql

volumes:
  pgdata:
    driver: local